system:
  host: 0.0.0.0
  port: 8080
  env: dev

mysql:
  host: local
  port: 3306
  user: root
  password: root

logger:
  level: debug
  prefix: "[inception]"
  show-line: true
  log-in-console: true


